targets:
  dev:
    default: true
    mode: development
    workspace:
      host: ${workspace.host}
    variables:
      dev_catalog: agentops_dev
      prod_catalog: agentops_prod
      model_serving_endpoint: agentops-dev-endpoint
      vector_search_endpoint: agentops-vs-dev-endpoint
    run_as:
      service_principal_name: ${workspace.current_user.userName}
